apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: gitea
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 3.*
      helm:
        releaseName: gitea
        valuesObject:
          resourcesPreset: "none"
          adminUsername: "admin"
          adminPassword: "admin"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
