---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.*
      helm:
        releaseName: loki
        valuesObject:
          chunksCache:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 250m
                memory: 512Mi
          resultsCache:
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          singleBinary:
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            schemaConfig:
              configs:
                - from: "2024-04-01"
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
            pattern_ingester:
                enabled: true
            limits_config:
              allow_structured_metadata: true
              volume_enabled: true
            ruler:
              enable_api: true
          gateway:
            resources:
              requests:
                cpu: 25m
                memory: 16Mi
              limits:
                cpu: 75m
                memory: 32Mi
          lokiCanary:
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                cpu: 25m
                memory: 32Mi
          minio:
            enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                cpu: 100m
                memory: 768Mi
          deploymentMode: SingleBinary
          singleBinary:
            replicas: 1
          # Zero out replica counts of other deployment modes
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0
          ingester:
            replicas: 0
          querier:
            replicas: 0
          queryFrontend:
            replicas: 0
          queryScheduler:
            replicas: 0
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomCompactor:
            replicas: 0
          bloomGateway:
            replicas: 0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

