---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - path: charts/telepresence
      repoURL: https://github.com/telepresenceio/telepresence
      targetRevision: v2.21.1
      helm:
        releaseName: traffic-manager
        valuesObject:
          agent:
            image:
              tag: 2.21.1
          image:
            tag: 2.21.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ambassador
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

